#include <inttypes.h>
#include <avr/io.h>
#include <avr/interrupt.h>

#define START_BUTTON PD2
#define START_BUTTON_DDR DDRD
#define STOP_BUTTON PD3
#define STOP_BUTTON_DDR DDRD
#define PROFILE1_SELECT PD4
#define PROFILE1_SELECT_DDR DDRD
#define PROFILE2_SELECT PB6
#define PROFILE2_SELECT_DDR DDRB
#define PROFILE3_SELECT PB7
#define PROFILE3_SELECT_DDR DDRB
#define PROFILE4_SELECT PD5
#define PROFILE4_SELECT_DDR DDRD

#define HEATER_PIN PD6
#define HEATER_PIN_DDR DDRD
#define FAN_PIN PD7
#define FAN_PIN_DDR DDRD

int main()
{
	START_BUTTON_DDR &= ~(1 << START_BUTTON);
	STOP_BUTTON_DDR &= ~(1 << STOP_BUTTON);

	PROFILE1_SELECT_DDR &= ~(1 << PROFILE1_SELECT);
	PROFILE2_SELECT_DDR &= ~(1 << PROFILE2_SELECT);
	PROFILE3_SELECT_DDR &= ~(1 << PROFILE3_SELECT);
	PROFILE4_SELECT_DDR &= ~(1 << PROFILE4_SELECT);

	HEATER_PIN_DDR |= (1 << HEATER_PIN);
	FAN_PIN_DDR |= (1 << FAN_PIN);

	
}